services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: EJARI
    healthcheck:
        test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10
    networks:
      - net
  
  web:
    build: .
    ports:
      - "80:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: EJARI
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net
    

networks:
  net:
    driver: bridge