---
    name: test nodejs app
    on:
      pull_request:
        branches:
          - main
    jobs:
      test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Use Node.js 20.11.0
          uses: actions/setup-node@v4
          with:
            node-version: 20.11.0
        - name: npm install, build, and test
          run: |
            docker run --name some-mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=EJARI -d mysql
            npm install
            npm test