---
    name: test nodejs app
    on:
      push:
        branches:
          - ci
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js 12.x
          uses: actions/setup-node@v1
          with:
            node-version: 12.x
        - name: npm install, build, and test
          run: |
            docker run --name some-mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=EJARI -d mysql
            npm install
            npm test